C:\Python27\python D:\test_equipment_configuration\C919_ICD_Processor\Ads2Gen\ADS2CONFIG_BP4.4.py -c -m -s --loglevel=INFO  --outdir=D:\test_equipment_configuration\ICD_output\929\Ads2 --devmap=D:\test_equipment_configuration\C919_ICD_Processor\DeviceMap\SSDL_DEVMAP-4.4-929.xlsx --mode=stim --inputtype=Excel --hfname=FDAS_L1,IMA_DM_L4,IMA_DM_L5,IMA_DM_R4,SYNOPTICMENUAPP_L,SYNOPTICMENUAPP_R,SYNOPTICPAGEAPP_L,SYNOPTICPAGEAPP_R,HF_IDULEFTINBOARD,HF_IDULEFTOUTBOARD,HF_IDUCENTER,HF_IDURIGHTINBOARD,HF_IDURIGHTOUTBOARD,VIRTUALCONTROLAPP_L,VIRTUALCONTROLAPP_R --workdir="D:\test_equipment_configuration\ICD_output\929\Excel"

C:\Python27\python D:\test_equipment_configuration\C919_ICD_Processor\Ads2Gen\ADS2CONFIG_BP4.4.py -c -m -s --loglevel=INFO  --outdir=D:\test_equipment_configuration\ICD_output\929\Ads2\CP --devmap=D:\test_equipment_configuration\C919_ICD_Processor\DeviceMap\SSDL_DEVMAP-4.4-929.xlsx --mode=sim --inputtype=Excel --hfname=HF_CCD1,HF_CCD2,HF_DCP1,HF_DCP2,HF_MKB1,HF_MKB2,HF_RCP --workdir="D:\test_equipment_configuration\ICD_output\929\Excel"

rem C:\Python27\python D:\test_equipment_configuration\C919_ICD_Processor\Ads2Gen\ADS2CONFIG.py -c -m -s --loglevel=INFO  --outdir=D:\test_equipment_configuration\ICD_output\929\Ads2 --devmap=D:\test_equipment_configuration\C919_ICD_Processor\DeviceMap\SSDL_DEVMAP-4.4-5.1.xlsx --mode=stim --inputtype=Excel --hfname=FDAS_L1,IMA_DM_L4,IMA_DM_L5,IMA_DM_R4,SYNOPTICMENUAPP_L,SYNOPTICMENUAPP_R,SYNOPTICPAGEAPP_L,SYNOPTICPAGEAPP_R,HF_IDULEFTINBOARD,HF_IDULEFTOUTBOARD,HF_IDUCENTER,HF_IDURIGHTINBOARD,HF_IDURIGHTOUTBOARD,VIRTUALCONTROLAPP_L,VIRTUALCONTROLAPP_R --workdir="D:\test_equipment_configuration\ICD_output\929\Excel"

C:\Python27\python D:\test_equipment_configuration\C919_ICD_Processor\Ads2Gen\ADS2CONFIG_BP4.4.py -c -m -s --loglevel=INFO  --outdir=D:\test_equipment_configuration\ICD_output\C929\ADS2 --devmap=D:\test_equipment_configuration\C919_ICD_Processor\DeviceMap\SSDL_DEVMAP-4.4-929.xlsx --mode=stim --inputtype=Excel --hfname=FDAS_L1,FDAS_L3,FDAS_R3,IMA_DM_L4,IMA_DM_L5,IMA_DM_R4,SYNOPTICMENUAPP_L,SYNOPTICMENUAPP_R,SYNOPTICPAGEAPP_L,SYNOPTICPAGEAPP_R,HF_IDULEFTINBOARD,HF_IDULEFTOUTBOARD,HF_IDUCENTER,HF_IDURIGHTINBOARD,HF_IDURIGHTOUTBOARD,VIRTUALCONTROLAPP_L,VIRTUALCONTROLAPP_R --workdir="D:\test_equipment_configuration\ICD_output\C929\Excel"

C:\Python27\python D:\test_equipment_configuration\C919_ICD_Processor\Ads2Gen\ADS2CONFIG_BP4.4.py -c -m -s --loglevel=INFO  --outdir=D:\test_equipment_configuration\ICD_output\C929\ADS2 --devmap=D:\test_equipment_configuration\C919_ICD_Processor\DeviceMap\SSDL_DEVMAP-4.4-929.xlsx --mode=stim --inputtype=Excel --hfname=HF_IDURIGHTINBOARD --workdir="D:\test_equipment_configuration\ICD_output\C929\Excel"
